#! /bin/bash

PWD=$(pwd)

if [[ -z "$COMPILE_FLAGS" ]]; then
    COMPILE_FLAGS="-I /home/kskr24/dev/cpp/sdl_game -I /home/kskr24/dev/cpp/sdl_game/lib -isystem /usr/include/glog -isystem /usr/include/boost -isystem /usr/include/c++/11 -isystem /usr/include/x86_64-linux-gnu/c++/11 -isystem /usr/include/c++/11/backward -isystem /usr/lib/gcc/x86_64-linux-gnu/11/include -isystem /usr/lib/gcc/x86_64-linux-gnu/11/include-fixed -isystem /usr/include/x86_64-linux-gnu -std=c++23"
fi

echo "["

for f in $(git ls-files '*.cpp'); do
    echo "{"
    echo "\"directory\": \"${PWD}\","
    echo "\"command\": \"g++ ${COMPILE_FLAGS} -o \\\"${f/%.cpp/.o}\\\" \\\"${f}\\\"\","
    echo "\"file\": \"${f}\""
    echo "}"
    echo ","
done | sed '$d'

echo "]"
